baseURL = 'https://singhcoder.github.io/'
languageCode = 'en-us'
title = 'My Personal Blog'
theme = 'flat'
googleAnalytics = 'G-TR6P06RWHL'
disqusShortname = 'singhcoder'
[params]
  description = "SinghCoder's personal blog"
  images = ['site-feature-image.jpg']
  google_site_verification = 'google-site-verification=VNEQK6FTsfRUopGbrsNiULofIx7b4Y6TSxzbH3hx_c0'
[social]
  twitter = 'singhhcoder'