baseURL = 'https://singhcoder.github.io/'
languageCode = 'en-us'
title = 'My Personal Blog'
theme = 'flat'
googleAnalytics = 'G-TR6P06RWHL'
disqusShortname = 'singhcoder'
[params]
  description = "SinghCoder's personal blog"
  images = ['site-feature-image.jpg']
  google_site_verification = 'google-site-verification=nrXJC1Q97Lp2aEB5iMkD7nNX0Mg3X2btPqho_kWMUts'
[social]
  twitter = 'singhhcoder'